# Default Configuration
# This file contains default settings

# Logging configuration
logging:
  level: info

# Retry configuration
retry:
  max_retries: 3
  base_delay: 1s
  max_delay: 30s

# Sources configuration
sources:
  dummy:
    enabled: false
    interval: 5s
